name: Push to DockerHub and Google Artifact Registry

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Docker Hub Auth
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Google Docker Artifact Registry Auth
        uses: docker/login-action@v3
        with:
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
          registry: ${{ vars.REGION }}-docker.pkg.dev
      
      - name: Define .env and Other Credential File
        run: |
          touch .env && echo "${{ secrets.ENV_FILE_BACKUP }}" > .env
          echo "${{ secrets.GCLOUD_BUCKET_CREDENTIAL_B64 }}" | base64 --decode > bucket-credential-candra.json

      - name: Push to Docker repo
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKER_IMAGE_URL }}
            ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID_GCP }}/${{ vars.GCLOUD_ARTIFACT_REPO }}/${{ vars.SERVICE_NAME }}:${{ github.sha }}
          # build-args: |
          #   MYSQL_URL=${{ secrets.MYSQL_URL }}
          #   REDIS_HOST=${{ secrets.REDIS_HOST }}
          #   REDIS_PORT=${{ secrets.REDIS_PORT }}
          #   REDIS_USERNAME=${{ secrets.REDIS_USERNAME }}
          #   REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
          #   MIDTRANS_SERVER_KEY=${{ secrets.MIDTRANS_SERVER_KEY }}
          #   GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          #   GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          #   DASHBOARD_REDIRECT_URL=${{ secrets.DASHBOARD_REDIRECT_URL }}

