name: Deploy to Production

on:
  workflow_run:
    workflows: ["Push to DockerHub and Google Artifact Registry"]
    types:
      - completed

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy-cloudrun.yml
    with:
      environment: production
      tag: ${{ github.sha }}
    secrets:
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      VPC_NETWORK: ${{ secrets.VPC_NETWORK }}
      VPC_SUBNET: ${{ secrets.VPC_SUBNET }}
      NETWORK_TAG: ${{ secrets.NETWORK_TAG }}
