name: Deploy to Production

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy-cloudrun.yml
    with:
      environment: production
      tag: ${{ github.sha }}
